### ISSUE TITLE
Should laws be included in the definition of categories in `Felix.Raw`?

### ISSUE THREAD

**Issue by AtticusKuhn** [conal/felix#2]
It seems to me a strange architectural/design descision to separate the categorical laws into `Felix.Laws`. What I mean is that the laws are intrinsically part of the definition; if something claims to be a category, but it is not associative, then it is not a category.

What I am imagining is something like this

```agda
record Category {obj : Set o} (_⇨_ : obj → obj → Set ℓ) : Set (o ⊔ ℓ) where
  infixr 9 _∘_
  field
    id  : a ⇨ a
    _∘_ : {a b c : obj} → (g : b ⇨ c) (f : a ⇨ b) → (a ⇨ c)
    identityˡ : {f : a ⇨ b} → id ∘ f ≡ f
    identityʳ : {f : a ⇨ b} → f ∘ id ≡ f
    assoc     : {f : a ⇨ b} {g : b ⇨ c} {h : c ⇨ d} → (h ∘ g) ∘ f ≡ h ∘ (g ∘ f)
```
The benefit of this is that we could delete the record fields such as `∘≈ ` , which just become automatically true.

There are also morphisms that really just appear to be equalities in disguise. One example is the `unitor` family, which is really
just the natural ismorphism that `a × ⊤ ≡ ⊤ × a ≡ a`. 

The reason I am making this an issue and not a pull request is that the maintainer probably has a good reason why `Felix.Raw` and `Felix.Laws` are split up into 2 files.

**Comment by conal** [comment]
> the maintainer probably has a good reason why `Felix.Raw` and `Felix.Laws` are split up into 2 files.

Indeed, he does!

**Comment by conal** [comment]
> The benefit of this is that we could delete the record fields such as `∘≈ ` , which just become automatically true.

Do they?

**Comment by conal** [comment]
> There are also morphisms that really just appear to be equalities in disguise. One example is the `unitor` family, which is really just the natural ismorphism that `a × ⊤ ≡ ⊤ × a ≡ a`.

Are they indeed equalities or just isomorphisms?

**Comment by AtticusKuhn** [comment]
> Are they indeed equalities or just isomorphisms?

Equalities are the same thing as isomorphisms. In the words of the univalence axiom, isomorphism is isomorphic to equality.

**Comment by AtticusKuhn** [comment]
>> The benefit of this is that we could delete the record fields such as ∘≈  , which just become automatically true.

> Do they?

Yes, 
```agda

{-# OPTIONS --cubical #-}

open import Level using (Level; _⊔_; suc)
open import Function using (const) renaming (id to id′; _∘_ to _∘̇_)

open import Cubical.Foundations.Prelude
private
  variable
    o ℓ o₁ ℓ₁ o₂ ℓ₂ : Level
    obj obj₁ obj₂ : Set o
    a b c d e s : obj
    a′ b′ c′ d′ e′ : obj

record Category {obj : Set o} (_⇨_ : obj → obj → Set ℓ) : Set (o ⊔ ℓ) where
  infixr 9 _∘_
  field
    id  : a ⇨ a
    _∘_ : {a b c : obj} → (g : b ⇨ c) (f : a ⇨ b) → (a ⇨ c)
    identityˡ : {f : a ⇨ b} → id ∘ f ≡ f
    identityʳ : {f : a ⇨ b} → f ∘ id ≡ f
    assoc     : {f : a ⇨ b} {g : b ⇨ c} {h : c ⇨ d} → (h ∘ g) ∘ f ≡ h ∘ (g ∘ f)



  ∘≈ : ∀ {f g : a ⇨ b} {h k : b ⇨ c} → h ≡ k → f ≡ g → (h ∘ f) ≡ (k ∘ g)
  ∘≈  h=k f=g i = (h=k i) ∘ (f=g i)
```

**Comment by conal** [comment]
> Yes, here is a minimal working example.

But you've changed the signature of `∘≈`.

**Comment by conal** [comment]
> Equalities are the same thing as isomorphisms. In the words of the univalence axiom, isomorphism is isomorphic to equality.

They're only the same *if* you assume univalence. Felix doesn't rely on axioms beyond MLTT.

**Comment by conal** [comment]
From [the project readme](https://github.com/conal/felix#readme):

> Felix: an Agda category theory for denotational design

This purpose motivated my choices to (a) use morphism equivalence instead of morphism equality and (b) separate “raw categories” from “(lawful) categories”.
