### ISSUE TITLE
nix incantation

### ISSUE THREAD

**Issue by bsaul** [conal/felix#4]
In case it's helpful to other `nix` users, I was able to install `felix` from github using nix as follows. I use nix flakes, but this could be adapted as needed. 

I have an `agda.nix` file:

```nix
-- agda.nix
{ pkgs }:
with pkgs;

agda.withPackages (p: 
  let stdlib = p.standard-library.overrideAttrs (oldAttrs: {
    version = "2.0";
    src = fetchFromGitHub {
      repo = "agda-stdlib";
      owner = "agda";
      rev = "46daf81a51a6e13a0cae107b3e51790f88da7c5c";
      sha256 = "YVVJiRhRhGXAcwg8m15tGEr/6oh4PLIAsoCsB9zWmaw=";
    };
  });
  
    felix = p.mkDerivation {
      pname = "felix";
      version = "0.1.0";
      meta = "";
      everythingFile = "src/Felix/All.agda";
      libraryFile = "felix.agda-lib";
      buildInputs = [
        stdlib
      ];
      src = fetchFromGitHub {
        repo = "felix";
        owner = "conal";
        version = "0.1.0";
        rev = "56bb608ec5c23fbbf42b79a7cdb4d5cfdc93256a";
        sha256 = "7y2jyORAYrm94BmgAfM/WUzaEdU28hFIci+p4HjUan4=";
      };
    };

  in
  [ stdlib
    felix
  ]
)
```
which I then source from `flake.nix` in the `outputs`:

```nix
  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system: let
      pkgs = nixpkgs.legacyPackages.${system};
      agda = pkgs.agda;
    in {
      devShells.default =  pkgs.mkShell {
        buildInputs = [

          # Adga
          # Info on Agda/nix: 
          # https://nixos.org/manual/nixpkgs/stable/#how-to-use-agda
          (import ./agda.nix {pkgs = pkgs;} )

        ];
      }; 
    });
```

**Comment by AtticusKuhn** [comment]
Thank you, this is very helpful.

**Comment by conal** [comment]
>           src = fetchFromGitHub {
>             repo = "felix";
>             owner = "conal";
>             version = "0.1.0";
>             rev = "56bb608ec5c23fbbf42b79a7cdb4d5cfdc93256a";
>             sha256 = "7y2jyORAYrm94BmgAfM/WUzaEdU28hFIci+p4HjUan4=";
>           };

To what does this `rev` refer? (I don’t know Nix.)

**Comment by bsaul** [comment]
> To what does this `rev` refer? (I don’t know Nix.)

The hash of specific git commit that will be fetched. I just grabbed the latest.

**Comment by bsaul** [comment]
I just made up a `version` number too. I think I could've used an empty string.

**Comment by conal** [comment]
> > To what does this `rev` refer? (I don’t know Nix.)
> 
> The hash of specific git commit that will be fetched. I just grabbed the latest.

Thanks. I was looking at the wrong end of the hashes.

How do library maintainers decide when to update the `rev` and `sha256` fields? And wouldn't different users want different versions?

**Comment by conal** [comment]
In other words, is there a maintenance story to go along with this suggestion?

**Comment by conal** [comment]
Oh---maybe you're not suggesting an addition to Felix.

**Comment by bsaul** [comment]
> How do library maintainers decide when to update the `rev` and `sha256` fields? 

When they want to or they know a new feature has been released or a bug fixed.

> And wouldn't different users want different versions?

Indeed. And they can, they just need to just the hash fields to whatever they need.

**Comment by bsaul** [comment]
> Oh---maybe you're not suggesting an addition to Felix.

Indeed, I'm not. If there's enough `nix` users that also use Felix; something like ☝🏼  could get added to the readme.

**Comment by bsaul** [comment]
@conal - feel free to close this issue. I'm just hoping to save others that use nix/my future self some pain.

**Comment by conal** [comment]
Much appreciated, @bsaul!
